name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checking out source code
        uses: actions/checkout@v2

      - name: Using Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Create .npmrc file
        run: |
          rm -f ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=$TOKEN" > ~/.npmrc
          echo "@autograders:registry=https://npm.pkg.github.com" >> ~/.npmrc
        env:
          TOKEN: ${{ secrets.GH_PKG_TOKEN }}

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Linting
        run: yarn lint

      - name: Coverage
        run: yarn coverage

      - name: Build application
        run: yarn build

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
